name: mobility_CI
on: # 워크플로우를 언제 실행할 것인가
  pull_request:
      branches: ["main", "dev"]
      paths-ignore:
        - 'README.md'

      concurrency:
        group: ${{ github.workflow }}-${{ github.ref }}
        cancel-in-progress: true

  permissions: # 권한 설정
    contents: read
    pull-requests: write

  jobs:
    build:
      runs-on: ubuntu-latest # 실행환경 지정

    # 실행 스텝 지정
      steps:
        - name: 코드 체크아웃
          uses: actions/checkout@v4

        - name: JDK 21 시작 # 환경 설치
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'

        - name: application-dev.properties 파일 주입
          run: |
            touch src/main/resources/application-dev.properties
            echo "${{ secrets.APPLICATION_DEV_PROPERTIES }}" > src/main/resources/application-dev.properties

        - name: Gradle 권한 부여
          run: chmod +x ./gradlew

        - name: Gradle 빌드 실행
          run: ./gradlew clean build --stacktrace